-- =============================================================================
-- Turbulent Boundary Layer SQL Analytics Pipeline
-- PostgreSQL schema definition for KTH DNS data (Schlatter & Örlü, 2010)
-- =============================================================================

CREATE TABLE IF NOT EXISTS simulation_conditions (
    condition_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    re_theta DOUBLE PRECISION NOT NULL UNIQUE,
    re_delta_star DOUBLE PRECISION,
    re_tau DOUBLE PRECISION,
    shape_factor DOUBLE PRECISION,
    cf DOUBLE PRECISION,
    u_tau DOUBLE PRECISION,
    delta_99 DOUBLE PRECISION,
    source_file TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS velocity_profiles (
    profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id INTEGER NOT NULL REFERENCES simulation_conditions(condition_id),
    y_delta DOUBLE PRECISION NOT NULL,
    y_plus DOUBLE PRECISION NOT NULL,
    u_plus DOUBLE PRECISION NOT NULL,
    u_rms_plus DOUBLE PRECISION NOT NULL,
    v_rms_plus DOUBLE PRECISION NOT NULL,
    w_rms_plus DOUBLE PRECISION NOT NULL,
    uv_plus DOUBLE PRECISION NOT NULL,
    p_rms_plus DOUBLE PRECISION,
    pu_plus DOUBLE PRECISION,
    pv_plus DOUBLE PRECISION,
    skewness_u DOUBLE PRECISION,
    flatness_u DOUBLE PRECISION,
    du_dy_plus DOUBLE PRECISION,
    v_plus DOUBLE PRECISION,
    omx_rms_plus DOUBLE PRECISION,
    omy_rms_plus DOUBLE PRECISION,
    omz_rms_plus DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (condition_id, y_plus)
);

CREATE INDEX IF NOT EXISTS idx_vp_condition ON velocity_profiles (condition_id);
CREATE INDEX IF NOT EXISTS idx_vp_yplus ON velocity_profiles (y_plus);
CREATE INDEX IF NOT EXISTS idx_vp_ydelta ON velocity_profiles (y_delta);

CREATE TABLE IF NOT EXISTS tke_budgets (
    budget_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id INTEGER NOT NULL REFERENCES simulation_conditions(condition_id),
    y_delta DOUBLE PRECISION NOT NULL,
    y_plus DOUBLE PRECISION NOT NULL,
    convection DOUBLE PRECISION,
    production DOUBLE PRECISION,
    dissipation DOUBLE PRECISION,
    turb_diffusion DOUBLE PRECISION,
    vel_pressure DOUBLE PRECISION,
    visc_diffusion DOUBLE PRECISION,
    residual DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (condition_id, y_plus)
);

CREATE INDEX IF NOT EXISTS idx_tke_condition ON tke_budgets (condition_id);
CREATE INDEX IF NOT EXISTS idx_tke_yplus ON tke_budgets (y_plus);

CREATE TABLE IF NOT EXISTS reynolds_stress_budgets (
    rs_budget_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id INTEGER NOT NULL REFERENCES simulation_conditions(condition_id),
    component TEXT NOT NULL CHECK (component IN ('uu', 'vv', 'ww', 'uv')),
    y_delta DOUBLE PRECISION NOT NULL,
    y_plus DOUBLE PRECISION NOT NULL,
    convection DOUBLE PRECISION,
    production DOUBLE PRECISION,
    dissipation DOUBLE PRECISION,
    turb_diffusion DOUBLE PRECISION,
    vel_pressure DOUBLE PRECISION,
    visc_diffusion DOUBLE PRECISION,
    residual DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (condition_id, component, y_plus)
);

CREATE INDEX IF NOT EXISTS idx_rs_condition ON reynolds_stress_budgets (condition_id);
CREATE INDEX IF NOT EXISTS idx_rs_component ON reynolds_stress_budgets (component);

CREATE TABLE IF NOT EXISTS derived_features (
    feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id INTEGER NOT NULL REFERENCES simulation_conditions(condition_id),
    re_theta DOUBLE PRECISION,
    tke_peak DOUBLE PRECISION,
    tke_peak_yplus DOUBLE PRECISION,
    u_rms_peak DOUBLE PRECISION,
    u_rms_peak_yplus DOUBLE PRECISION,
    production_peak DOUBLE PRECISION,
    dissipation_wall DOUBLE PRECISION,
    log_layer_slope DOUBLE PRECISION,
    wake_strength DOUBLE PRECISION,
    anisotropy_ratio_peak DOUBLE PRECISION,
    shape_factor DOUBLE PRECISION,
    cf DOUBLE PRECISION,
    re_tau DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (condition_id)
);

CREATE TABLE IF NOT EXISTS predictions (
    prediction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id INTEGER NOT NULL REFERENCES simulation_conditions(condition_id),
    model_name TEXT NOT NULL,
    model_version TEXT,
    predicted_re_tau DOUBLE PRECISION,
    predicted_cf DOUBLE PRECISION,
    cluster_label INTEGER,
    anomaly_score DOUBLE PRECISION,
    is_anomaly BOOLEAN DEFAULT FALSE,
    predicted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pred_model ON predictions (model_name);

CREATE TABLE IF NOT EXISTS model_registry (
    model_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,
    model_version TEXT NOT NULL,
    model_type TEXT NOT NULL,
    hyperparameters TEXT,
    metric_name TEXT,
    metric_value DOUBLE PRECISION,
    n_training_samples INTEGER,
    training_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    UNIQUE (model_name, model_version)
);
